In [1]:
import pandas as pd
import numpy as np
import datetime
import os

In [2]:
df_cases = pd.read_csv("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Cumulative%20cases.csv")

In [3]:
hbo_dict = {
    
    1 : 'Ayrshire and Arran',
    2 : 'Borders',
    3 : 'Dumfries and Galloway',
    4 : 'Western Isles',
    5 : 'Fife',
    6 : 'Forth Valley',
    7 : 'Grampian',
    8 : 'Greater Glasgow and Clyde',
    9 : 'Highland',
    10 : 'Lanarkshire',
    11 : 'Lothian',
    12 : 'Orkney',
    13 : 'Shetland',
    14 : 'Tayside'
}

In [4]:
path_dict = {
                "cases" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Cumulative%20cases.csv",
                "hospital_covid" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients%20-%20Confirmed.csv",
                "hospital_all" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients.csv",
                "icu" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20ICU%20patients.csv",
            }

In [5]:
df_cases.tail()

,Date,Ayrshire and Arran,Borders,Dumfries and Galloway,Fife,Forth Valley,Grampian,Greater Glasgow and Clyde,Highland,Lanarkshire,Lothian,Orkney,Shetland,Tayside,Western Isles
74,2020-05-20,987,322,257,826,894,1216,3780,334,1867,2584,7,54,1617,6
75,2020-05-21,995,322,257,826,896,1218,3806,334,1892,2611,7,54,1632,6
76,2020-05-22,1001,322,257,826,909,1223,3841,335,1913,2634,7,54,1641,6
77,2020-05-23,1015,322,257,826,915,1223,3865,335,1922,2649,7,54,1645,6
78,2020-05-24,1019,322,258,826,917,1224,3876,335,1934,2665,7,54,1658,6

In [6]:
def get_hbo_data_by_date(health_board, data_type):
    df = pd.read_csv(path_dict.get(data_type))
    df = df[['Date', health_board]]
    df = df.rename(columns={'Date':'date', health_board:'value'})
    df['value'] = df['value'].astype(int)
    df['value'] = df[['value']].diff()
    df = df.iloc[-31:]
    return df

In [10]:
df_test = get_hbo_data_by_date('Grampian', "cases")
df_test['value'] = df_test['value'].astype(int)

In [11]:
df_test['value'] = df_test[['value']].diff()

In [13]:
df_test.head()

          date  value
48  2020-04-24    NaN
49  2020-04-25   62.0
50  2020-04-26   48.0
51  2020-04-27   23.0
52  2020-04-28   11.0

In [ ]:
def get_all_hbo_data(path_dict, root_path):
    
    for i in range (1, len(hbo_dict)+1):
            
        # Create the dataframe
        #print(hbo_dict[i])
        df = get_hbo_data_by_date(hbo_dict[i], data_type)
        path = root_path + f"{i}_{data_type}.csv"
        current_dir = os.getcwd()
        curr = os.path.dirname(os.getcwd())
        #print(curr)
        df.to_csv(current_dir + path)