In [1]:
import pandas as pd
import numpy as np
import zipfile
from io import BytesIO
from zipfile import ZipFile
from urllib.request import urlopen
import datetime
import urllib.request, urllib.error
import os.path

## Getting JSON Information

In [2]:
path = "/Users/markswan/Projects/covid-maps/data/sco_covid_data/covid-deaths-data-week-18/covid-deaths-data-week-18_Table1-COVID_deaths.csv"
path2 = "data/sco_covid_data/covid-deaths-data-week-18 /covid-deaths-data-week-18_Table1-COVID_deaths.csv"

covid_deaths_df = pd.read_csv(path2, header=3, encoding='unicode-escape')

In [3]:
covid_deaths_small = covid_deaths_df.iloc[:, 1:22]

In [4]:
all_deaths_path = "data/sco_covid_data/custom_data/all_deaths_lad_18.csv"
covid_deaths_path = "data/sco_covid_data/custom_data/covid_deaths_lad_18.csv"
loc_deaths_all_path = "data/sco_covid_data/custom_data/deaths_by_location_all_lad_18.csv"
loc_deaths_corona_path = "data/sco_covid_data/custom_data/deaths_by_location_corona_lad_18.csv"

In [5]:
df_all_deaths = pd.read_csv(all_deaths_path, header=1)

In [6]:
json_output = df_all_deaths.to_json(index=2)

# Getting Data From Github Daily

The following Github Repo https://github.com/DataScienceScotland/COVID-19-Management-Information contains information regarding scottish information which is pulled on a daily basis.

## Weekly Data by Local Authority
Source: https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/general-publications/weekly-and-monthly-data-on-births-and-deaths/deaths-involving-coronavirus-covid-19-in-scotland

In [7]:
# Get the current week number
week_num = datetime.date.today().isocalendar()[1]

In [8]:
def get_week_num():
    return datetime.date.today().isocalendar()[1]

In [9]:
def get_all_deaths_df(path):
            
    # Try get get the most recent data
    try:
        url = path + "covid-deaths-data-week-%d.zip" % get_week_num()
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        df_covid_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 1 - COVID deaths.csv'),header = 3, encoding='unicode-escape')
        df_all_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 2 - All deaths.csv'),header = 3, encoding='unicode-escape')
        
        df_covid_deaths_trimmed = df_covid_deaths.iloc[48:80, 1:get_week_num()+1]
        df_all_deaths_trimmed = df_all_deaths.iloc[50:82, 1:get_week_num()+1]

        
        return df_all_deaths_trimmed, df_covid_deaths_trimmed
    
    # If error, then get last week response
    except urllib.error.HTTPError as e:
        url = path + "covid-deaths-data-week-%d.zip" % (get_week_num()-1)
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        df_covid_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 1 - COVID deaths.csv'),header = 3, encoding='unicode-escape')
        df_all_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 2 - All deaths.csv'),header = 3, encoding='unicode-escape')
        
        df_covid_deaths_trimmed = df_covid_deaths.iloc[48:80, 1:get_week_num()+1]
        df_all_deaths_trimmed = df_all_deaths.iloc[50:82, 1:get_week_num()+1]

        
        return df_all_deaths_trimmed

In [10]:
def get_covid_deaths_df(path):
            
    # Try get get the most recent data
    try:
        url = path + "covid-deaths-data-week-%d.zip" % get_week_num()
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        df_covid_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 1 - COVID deaths.csv'),header = 3, encoding='unicode-escape')
        df_all_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 2 - All deaths.csv'),header = 3, encoding='unicode-escape')
        
        df_covid_deaths_trimmed = df_covid_deaths.iloc[48:80, 1:get_week_num()+1]
        df_all_deaths_trimmed = df_all_deaths.iloc[50:82, 1:get_week_num()+1]

        
        return df_all_deaths_trimmed, df_covid_deaths_trimmed
    
    # If error, then get last week response
    except urllib.error.HTTPError as e:
        url = path + "covid-deaths-data-week-%d.zip" % (get_week_num()-1)
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        df_covid_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 1 - COVID deaths.csv'),header = 3, encoding='unicode-escape')
        df_all_deaths = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 2 - All deaths.csv'),header = 3, encoding='unicode-escape')
        df_location = pd.read_csv(zipfile.open('covid-deaths-data-week-18_Table 3 - deaths by location.csv'), encoding='unicode-escape')
        
        df_covid_deaths_trimmed = df_covid_deaths.iloc[48:80, 1:get_week_num()+1]
        df_all_deaths_trimmed = df_all_deaths.iloc[50:82, 1:get_week_num()+1]
        

        
        return df_covid_deaths_trimmed

In [11]:
path = "https://www.nrscotland.gov.uk/files//statistics/covid19/"
df_all_deaths_trimmed = get_covid_deaths_df(path)

HTTPError: HTTP Error 404: Not Found

In [12]:
df_all_deaths_trimmed

NameError: name 'df_all_deaths_trimmed' is not defined

In [13]:
def get_death_locations_df(path, week):
            
    # Try get get the most recent data
    try:
        url = path + "covid-deaths-data-week-%d.zip" % week
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        df_location = pd.read_csv(zipfile.open('covid-deaths-data-week-%d_Table 3 - deaths by location.csv' % week), header=3, encoding='unicode-escape')
        idx_start = np.where(df_location['Unnamed: 0'] == 'Aberdeen City')[0][0]
        idx_end = idx_start + 32
        df_location_trimmed = df_location.iloc[idx_start:idx_end, :-2]

        
        return df_location_trimmed
    
    # If error, then get last week response
    except urllib.error.HTTPError as e:
        url = path + "covid-deaths-data-week-%d.zip" % week-1
        conn = urllib.request.urlopen(url)
        zipfile = ZipFile(BytesIO(conn.read()))
        
        
        df_location = pd.read_csv(zipfile.open('covid-deaths-data-week-%d_Table 3 - deaths by location.csv' % week), header=3, encoding='unicode-escape')

        idx_start = np.where(df_location['Unnamed: 0'] == 'Aberdeen City')[0][0]
        print(idx_start)
        idx_end = idx_start + 32
        df_location_trimmed = df_location.iloc[idx_start:idx_end, :-2]
        return df_location_trimmed

In [15]:
path = "https://www.nrscotland.gov.uk/files//statistics/covid19/"
df_death_locations_trimmed = get_death_locations_df(path, 19)
df_death_locations_trimmed

,Unnamed: 0,Care\nHome,Home / Non-institution,Hospital,Other\ninstitution3,All locations,Unnamed: 6,Care\nHome.1,Home / Non-institution.1,Hospital.1,Other\ninstitution3.1,All locations.1
21,Aberdeen City,40,5.0,33,0.0,78,NaN,238,237,443,0.0,918
22,Aberdeenshire,51,11.0,37,0.0,99,NaN,325,322,485,2.0,"1,134"
23,Angus,33,4.0,17,0.0,54,NaN,164,186,242,0.0,592
24,Argyll and Bute,22,8.0,28,0.0,58,NaN,106,188,201,0.0,495
25,City of Edinburgh,191,16.0,114,0.0,321,NaN,733,517,823,0.0,"2,073"
26,Clackmannanshire,26,1.0,8,0.0,35,NaN,98,74,100,2.0,274
27,Dumfries and Galloway,9,1.0,36,0.0,46,NaN,165,252,404,0.0,821
28,Dundee City,55,13.0,56,0.0,124,NaN,194,244,391,0.0,829
29,East Ayrshire,24,5.0,32,0.0,61,NaN,132,205,308,1.0,646
30,East Dunbartonshire,55,4.0,29,0.0,88,NaN,198,145,207,0.0,550
31,East Lothian,47,4.0,20,0.0,71,NaN,163,122,211,0.0,496
32,East Renfrewshire,40,3.0,35,0.0,78,NaN,144,111,168,1.0,424
33,Falkirk,52,10.0,41,0.0,103,NaN,243,238,344,0.0,825
34,Fife,59,15.0,88,0.0,162,NaN,410,507,782,0.0,"1,699"
35,Glasgow City,201,21.0,288,0.0,510,NaN,845,850,"1,283",5.0,"2,983"
36,Highland,9,5.0,25,0.0,39,NaN,276,344,442,0.0,"1,062"
37,Inverclyde,34,11.0,58,0.0,103,NaN,162,161,251,0.0,574
38,Midlothian,58,4.0,32,0.0,94,NaN,150,98,185,0.0,433
39,Moray,2,4.0,4,0.0,10,NaN,82,152,175,0.0,409
40,Na h-Eileanan Siar,0,0.0,0,0.0,0,NaN,49,41,55,0.0,145
41,North Ayrshire,33,9.0,33,0.0,75,NaN,185,221,361,1.0,768
42,North Lanarkshire,70,17.0,122,1.0,210,NaN,373,573,780,9.0,"1,735"
43,Orkney Islands,0,0.0,2,0.0,2,NaN,10,67,11,0.0,88
44,Perth and Kinross,17,4.0,33,0.0,54,NaN,225,198,330,18.0,771
45,Renfrewshire,79,8.0,73,0.0,160,NaN,326,253,392,5.0,976
46,Scottish Borders,3,5.0,40,0.0,48,NaN,94,148,282,49.0,573
47,Shetland Islands,5,0.0,2,0.0,7,NaN,39,21,27,0.0,87
48,South Ayrshire,41,5.0,38,0.0,84,NaN,210,173,304,0.0,687
49,South Lanarkshire,96,24.0,106,0.0,226,NaN,473,500,699,3.0,"1,675"
50,Stirling,17,7.0,25,0.0,49,NaN,117,122,161,1.0,401
51,West Dunbartonshire,48,4.0,47,0.0,99,NaN,143,175,203,0.0,521
52,West Lothian,21,9.0,35,0.0,65,NaN,159,235,343,0.0,737

In [16]:
df_death_locations_trimmed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 21 to 52
Data columns (total 12 columns):
Unnamed: 0                  32 non-null object
Care
Home                   32 non-null object
Home / Non-institution      32 non-null float64
Hospital                    32 non-null object
Other
institution3          32 non-null float64
All locations               32 non-null object
Unnamed: 6                  0 non-null float64
Care
Home.1                 32 non-null object
Home / Non-institution.1    32 non-null object
Hospital.1                  32 non-null object
Other
institution3.1        32 non-null float64
All locations.1             32 non-null object
dtypes: float64(4), object(8)
memory usage: 3.1+ KB

In [17]:
np.where(df_death_locations_trimmed['Unnamed: 0'] == 'Aberdeen City')[0][0]

0

In [20]:
def create_all_data_df(path):
    
    dict_id = {"S12000033":"Aberdeen City","S12000034":"Aberdeenshire","S12000041":"Angus","S12000035":"Argyll and Bute","S12000036":"City of Edinburgh","S12000005":"Clackmannanshire","S12000006":"Dumfries and Galloway","S12000042":"Dundee City","S12000008":"East Ayrshire","S12000045":"East Dunbartonshire","S12000010":"East Lothian","S12000011":"East Renfrewshire","S12000014":"Falkirk","S12000015":"Fife","S12000046":"Glasgow City","S12000017":"Highland","S12000018":"Inverclyde","S12000019":"Midlothian","S12000020":"Moray","S12000013":"Na h-Eileanan Siar","S12000021":"North Ayrshire","S12000044":"North Lanarkshire","S12000023":"Orkney Islands","S12000024":"Perth and Kinross","S12000038":"Renfrewshire","S12000026":"Scottish Borders","S12000027":"Shetland Islands","S12000028":"South Ayrshire","S12000029":"South Lanarkshire","S12000030":"Stirling","S12000039":"West Dunbartonshire","S12000040":"West Lothian"}
    
    df_death_locations = get_death_locations_df(path, 19)
    
    df_all = df_death_locations.reset_index(drop=True, inplace=False)
    headings = ['lad', 'covid_deaths_carehome', 'covid_deaths_non-institution', 'covid_deaths_hospital', 'covid_deaths_other', 'covid_deaths_total', 'blank1', 'all_deaths_carehome', 'all_deaths_non-institution', 'all_deaths_hospital', 'all_deaths_other', 'all_deaths_total']
    df_all.columns = headings        
    # Add the ratios
    
    df_all['ratio_hospital_death_covid'] = (df_all['covid_deaths_hospital'].str.replace(',', '').astype(float) / df_all['all_deaths_hospital'].str.replace(',', '').astype(float)) * 100
    df_all['ratio_carehome_death_covid'] = (df_all['covid_deaths_carehome'].str.replace(',', '').astype(float) / df_all['all_deaths_carehome'].str.replace(',', '').astype(float)) * 100
    df_all['ratio_total_death_covid'] = (df_all['covid_deaths_total'].str.replace(',', '').astype(float) / df_all['all_deaths_total'].str.replace(',', '').astype(float)) * 100
    df_all = df_all.drop(['blank1'], axis=1)
    df_all = df_all.round(1)
    df_all['id'] = dict_id.keys()
    df_all = df_all.set_index('id')
    return df_all

In [21]:
path = "https://www.nrscotland.gov.uk/files//statistics/covid19/"
df_all = create_all_data_df(path)
df_all

,lad,covid_deaths_carehome,covid_deaths_non-institution,covid_deaths_hospital,covid_deaths_other,covid_deaths_total,all_deaths_carehome,all_deaths_non-institution,all_deaths_hospital,all_deaths_other,all_deaths_total,ratio_hospital_death_covid,ratio_carehome_death_covid,ratio_total_death_covid
id,,,,,,,,,,,,,,
S12000033,Aberdeen City,40,5.0,33,0.0,78,238,237,443,0.0,918,7.4,16.8,8.5
S12000034,Aberdeenshire,51,11.0,37,0.0,99,325,322,485,2.0,"1,134",7.6,15.7,8.7
S12000041,Angus,33,4.0,17,0.0,54,164,186,242,0.0,592,7.0,20.1,9.1
S12000035,Argyll and Bute,22,8.0,28,0.0,58,106,188,201,0.0,495,13.9,20.8,11.7
S12000036,City of Edinburgh,191,16.0,114,0.0,321,733,517,823,0.0,"2,073",13.9,26.1,15.5
S12000005,Clackmannanshire,26,1.0,8,0.0,35,98,74,100,2.0,274,8.0,26.5,12.8
S12000006,Dumfries and Galloway,9,1.0,36,0.0,46,165,252,404,0.0,821,8.9,5.5,5.6
S12000042,Dundee City,55,13.0,56,0.0,124,194,244,391,0.0,829,14.3,28.4,15.0
S12000008,East Ayrshire,24,5.0,32,0.0,61,132,205,308,1.0,646,10.4,18.2,9.4
S12000045,East Dunbartonshire,55,4.0,29,0.0,88,198,145,207,0.0,550,14.0,27.8,16.0
S12000010,East Lothian,47,4.0,20,0.0,71,163,122,211,0.0,496,9.5,28.8,14.3
S12000011,East Renfrewshire,40,3.0,35,0.0,78,144,111,168,1.0,424,20.8,27.8,18.4
S12000014,Falkirk,52,10.0,41,0.0,103,243,238,344,0.0,825,11.9,21.4,12.5
S12000015,Fife,59,15.0,88,0.0,162,410,507,782,0.0,"1,699",11.3,14.4,9.5
S12000046,Glasgow City,201,21.0,288,0.0,510,845,850,"1,283",5.0,"2,983",22.4,23.8,17.1
S12000017,Highland,9,5.0,25,0.0,39,276,344,442,0.0,"1,062",5.7,3.3,3.7
S12000018,Inverclyde,34,11.0,58,0.0,103,162,161,251,0.0,574,23.1,21.0,17.9
S12000019,Midlothian,58,4.0,32,0.0,94,150,98,185,0.0,433,17.3,38.7,21.7
S12000020,Moray,2,4.0,4,0.0,10,82,152,175,0.0,409,2.3,2.4,2.4
S12000013,Na h-Eileanan Siar,0,0.0,0,0.0,0,49,41,55,0.0,145,0.0,0.0,0.0
S12000021,North Ayrshire,33,9.0,33,0.0,75,185,221,361,1.0,768,9.1,17.8,9.8
S12000044,North Lanarkshire,70,17.0,122,1.0,210,373,573,780,9.0,"1,735",15.6,18.8,12.1
S12000023,Orkney Islands,0,0.0,2,0.0,2,10,67,11,0.0,88,18.2,0.0,2.3
S12000024,Perth and Kinross,17,4.0,33,0.0,54,225,198,330,18.0,771,10.0,7.6,7.0
S12000038,Renfrewshire,79,8.0,73,0.0,160,326,253,392,5.0,976,18.6,24.2,16.4
S12000026,Scottish Borders,3,5.0,40,0.0,48,94,148,282,49.0,573,14.2,3.2,8.4
S12000027,Shetland Islands,5,0.0,2,0.0,7,39,21,27,0.0,87,7.4,12.8,8.0
S12000028,South Ayrshire,41,5.0,38,0.0,84,210,173,304,0.0,687,12.5,19.5,12.2
S12000029,South Lanarkshire,96,24.0,106,0.0,226,473,500,699,3.0,"1,675",15.2,20.3,13.5
S12000030,Stirling,17,7.0,25,0.0,49,117,122,161,1.0,401,15.5,14.5,12.2
S12000039,West Dunbartonshire,48,4.0,47,0.0,99,143,175,203,0.0,521,23.2,33.6,19.0
S12000040,West Lothian,21,9.0,35,0.0,65,159,235,343,0.0,737,10.2,13.2,8.8

In [22]:
def convert_all_types(df_all):

    df_all['covid_deaths_carehome'] = df_all['covid_deaths_carehome'].astype(int)
    df_all['covid_deaths_non-institution'] = df_all['covid_deaths_non-institution'].astype(int)
    df_all['covid_deaths_hospital'] = df_all['covid_deaths_hospital'].str.replace(',', '').astype(float)
    df_all['covid_deaths_other'] = df_all['covid_deaths_other'].astype(int)
    df_all['covid_deaths_total'] = df_all['covid_deaths_total'].astype(int)
    df_all['all_deaths_carehome'] = df_all['all_deaths_carehome'].astype(int)
    df_all['all_deaths_non-institution'] = df_all['all_deaths_non-institution'].astype(float)
    df_all['all_deaths_hospital'] = df_all['all_deaths_hospital']
    df_all['all_deaths_other'] = df_all['all_deaths_other'].astype(int)
    df_all['all_deaths_total'] = df_all['all_deaths_total'].str.replace(',', '').astype(float)
    df_all['all_deaths_hospital'] = df_all['all_deaths_hospital'].str.replace(',', '').astype(float)
    df_all['all_deaths_other'] = df_all['all_deaths_other'].astype(int)
    
    return df_all

In [597]:
def send_df_as_json(df_all_data, output_path):
    
    with open(os.path.join("https://raw.githubusercontent.com/markjswan/covid-maps/master/json/sco/", 'test123.json'), "w") as file:
        file.write(df_all_data.to_json('test345.json'))

In [589]:
json = send_df_as_json(df_all)

In [590]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, S12000033 to S12000040
Data columns (total 14 columns):
lad                             32 non-null object
covid_deaths_carehome           32 non-null object
covid_deaths_non-institution    32 non-null float64
covid_deaths_hospital           32 non-null object
covid_deaths_other              32 non-null float64
covid_deaths_total              32 non-null object
all_deaths_carehome             32 non-null object
all_deaths_non-institution      32 non-null object
all_deaths_hospital             32 non-null object
all_deaths_other                32 non-null float64
all_deaths_total                32 non-null object
ratio_hospital_death_covid      32 non-null float64
ratio_carehome_death_covid      32 non-null float64
ratio_total_death_covid         32 non-null float64
dtypes: float64(6), object(8)
memory usage: 5.0+ KB

In [592]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, S12000033 to S12000040
Data columns (total 14 columns):
lad                             32 non-null object
covid_deaths_carehome           32 non-null int64
covid_deaths_non-institution    32 non-null int64
covid_deaths_hospital           32 non-null float64
covid_deaths_other              32 non-null int64
covid_deaths_total              32 non-null int64
all_deaths_carehome             32 non-null int64
all_deaths_non-institution      32 non-null float64
all_deaths_hospital             32 non-null float64
all_deaths_other                32 non-null int64
all_deaths_total                32 non-null float64
ratio_hospital_death_covid      32 non-null float64
ratio_carehome_death_covid      32 non-null float64
ratio_total_death_covid         32 non-null float64
dtypes: float64(7), int64(6), object(1)
memory usage: 5.0+ KB

In [23]:
headings = ['lad', 'covid_deaths_carehome', 'covid_deaths_non-institution', 'covid_deaths_hospital', 'covid_deaths_other', 'covid_deaths_total', 'all_deaths_carehome', 'all_deaths_non-institution', 'all_deaths_hospital', 'all_deaths_other', 'all_deaths_total']
df_all[headings].replace({',':''}, regex=True)

,lad,covid_deaths_carehome,covid_deaths_non-institution,covid_deaths_hospital,covid_deaths_other,covid_deaths_total,all_deaths_carehome,all_deaths_non-institution,all_deaths_hospital,all_deaths_other,all_deaths_total
id,,,,,,,,,,,
S12000033,Aberdeen City,40,5.0,33,0.0,78,238,237,443,0.0,918
S12000034,Aberdeenshire,51,11.0,37,0.0,99,325,322,485,2.0,1134
S12000041,Angus,33,4.0,17,0.0,54,164,186,242,0.0,592
S12000035,Argyll and Bute,22,8.0,28,0.0,58,106,188,201,0.0,495
S12000036,City of Edinburgh,191,16.0,114,0.0,321,733,517,823,0.0,2073
S12000005,Clackmannanshire,26,1.0,8,0.0,35,98,74,100,2.0,274
S12000006,Dumfries and Galloway,9,1.0,36,0.0,46,165,252,404,0.0,821
S12000042,Dundee City,55,13.0,56,0.0,124,194,244,391,0.0,829
S12000008,East Ayrshire,24,5.0,32,0.0,61,132,205,308,1.0,646
S12000045,East Dunbartonshire,55,4.0,29,0.0,88,198,145,207,0.0,550
S12000010,East Lothian,47,4.0,20,0.0,71,163,122,211,0.0,496
S12000011,East Renfrewshire,40,3.0,35,0.0,78,144,111,168,1.0,424
S12000014,Falkirk,52,10.0,41,0.0,103,243,238,344,0.0,825
S12000015,Fife,59,15.0,88,0.0,162,410,507,782,0.0,1699
S12000046,Glasgow City,201,21.0,288,0.0,510,845,850,1283,5.0,2983
S12000017,Highland,9,5.0,25,0.0,39,276,344,442,0.0,1062
S12000018,Inverclyde,34,11.0,58,0.0,103,162,161,251,0.0,574
S12000019,Midlothian,58,4.0,32,0.0,94,150,98,185,0.0,433
S12000020,Moray,2,4.0,4,0.0,10,82,152,175,0.0,409
S12000013,Na h-Eileanan Siar,0,0.0,0,0.0,0,49,41,55,0.0,145
S12000021,North Ayrshire,33,9.0,33,0.0,75,185,221,361,1.0,768
S12000044,North Lanarkshire,70,17.0,122,1.0,210,373,573,780,9.0,1735
S12000023,Orkney Islands,0,0.0,2,0.0,2,10,67,11,0.0,88
S12000024,Perth and Kinross,17,4.0,33,0.0,54,225,198,330,18.0,771
S12000038,Renfrewshire,79,8.0,73,0.0,160,326,253,392,5.0,976
S12000026,Scottish Borders,3,5.0,40,0.0,48,94,148,282,49.0,573
S12000027,Shetland Islands,5,0.0,2,0.0,7,39,21,27,0.0,87
S12000028,South Ayrshire,41,5.0,38,0.0,84,210,173,304,0.0,687
S12000029,South Lanarkshire,96,24.0,106,0.0,226,473,500,699,3.0,1675
S12000030,Stirling,17,7.0,25,0.0,49,117,122,161,1.0,401
S12000039,West Dunbartonshire,48,4.0,47,0.0,99,143,175,203,0.0,521
S12000040,West Lothian,21,9.0,35,0.0,65,159,235,343,0.0,737

In [24]:
df_all.info()
df_all.to_json('table_data_updated.json')

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, S12000033 to S12000040
Data columns (total 14 columns):
lad                             32 non-null object
covid_deaths_carehome           32 non-null object
covid_deaths_non-institution    32 non-null float64
covid_deaths_hospital           32 non-null object
covid_deaths_other              32 non-null float64
covid_deaths_total              32 non-null object
all_deaths_carehome             32 non-null object
all_deaths_non-institution      32 non-null object
all_deaths_hospital             32 non-null object
all_deaths_other                32 non-null float64
all_deaths_total                32 non-null object
ratio_hospital_death_covid      32 non-null float64
ratio_carehome_death_covid      32 non-null float64
ratio_total_death_covid         32 non-null float64
dtypes: float64(6), object(8)
memory usage: 3.8+ KB

In [14]:
custom_id = "data/sco_covid_data/custom_data/all_data_custom_id.csv"
df_custom = pd.read_csv(custom_id, header=1)

In [15]:
df_custom

,id,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,S12000033,Aberdeen City,425,227,229,0,881,27,32,4,0,63,0.064,0.141,0.017,0.072
1,S12000034,Aberdeenshire,461,308,299,2,1070,32,45,11,0,88,0.069,0.146,0.037,0.082
2,S12000041,Angus,234,152,180,0,566,14,31,4,0,49,0.060,0.204,0.022,0.087
3,S12000035,Argyll and Bute,197,100,174,0,471,26,21,8,0,55,0.132,0.210,0.046,0.117
4,S12000036,City of Edinburgh,793,679,486,0,1958,108,157,13,0,278,0.136,0.231,0.027,0.142
5,S12000005,Clackmannanshire,96,85,70,2,253,8,17,1,0,26,0.083,0.200,0.014,0.103
6,S12000006,Dumfries and Galloway,389,160,237,0,786,31,8,1,0,40,0.080,0.050,0.004,0.051
7,S12000042,Dundee City,376,180,232,0,788,50,46,11,0,107,0.133,0.256,0.047,0.136
8,S12000008,East Ayrshire,287,125,200,1,613,25,19,5,0,49,0.087,0.152,0.025,0.080
9,S12000045,East Dunbartonshire,197,180,134,0,511,24,40,2,0,66,0.122,0.222,0.015,0.129
10,S12000010,East Lothian,206,148,119,0,473,20,40,4,0,64,0.097,0.270,0.034,0.135
11,S12000011,East Renfrewshire,158,125,106,1,390,31,25,2,0,58,0.196,0.200,0.019,0.149
12,S12000014,Falkirk,324,218,229,0,771,39,38,9,0,86,0.120,0.174,0.039,0.112
13,S12000015,Fife,741,387,480,0,1608,74,54,15,0,143,0.100,0.140,0.031,0.089
14,S12000046,Glasgow City,1224,785,806,5,2820,264,169,19,0,452,0.216,0.215,0.024,0.160
15,S12000017,Highland,421,258,324,0,1003,25,3,5,0,33,0.059,0.012,0.015,0.033
16,S12000018,Inverclyde,240,154,152,0,546,57,31,11,0,99,0.238,0.201,0.072,0.181
17,S12000019,Midlothian,180,131,93,0,404,29,42,4,0,75,0.161,0.321,0.043,0.186
18,S12000020,Moray,165,74,142,0,381,2,2,4,0,8,0.012,0.027,0.028,0.021
19,S12000013,Na h-Eileanan Siar,55,49,39,0,143,0,0,0,0,0,0.000,0.000,0.000,0.000
20,S12000021,North Ayrshire,346,174,206,1,727,30,29,9,0,68,0.087,0.167,0.044,0.094
21,S12000044,North Lanarkshire,740,348,535,9,1632,114,65,15,1,195,0.154,0.187,0.028,0.119
22,S12000023,Orkney Islands,10,10,66,0,86,2,0,0,0,2,0.200,0.000,0.000,0.023
23,S12000024,Perth and Kinross,319,212,187,18,736,28,11,4,0,43,0.088,0.052,0.021,0.058
24,S12000038,Renfrewshire,370,309,239,5,923,69,72,8,0,149,0.186,0.233,0.033,0.161
25,S12000026,Scottish Borders,270,91,139,49,549,38,3,4,0,45,0.141,0.033,0.029,0.082
26,S12000027,Shetland Islands,25,37,19,0,81,2,5,0,0,7,0.080,0.135,0.000,0.086
27,S12000028,South Ayrshire,293,200,167,0,660,32,38,5,0,75,0.109,0.190,0.030,0.114
28,S12000029,South Lanarkshire,659,440,469,3,1571,85,84,21,0,190,0.129,0.191,0.045,0.121
29,S12000030,Stirling,155,108,108,1,372,25,14,5,0,44,0.161,0.130,0.046,0.118
30,S12000039,West Dunbartonshire,194,130,168,0,492,41,41,4,0,86,0.211,0.315,0.024,0.175
31,S12000040,West Lothian,327,145,223,0,695,31,13,8,0,52,0.095,0.090,0.036,0.075

In [16]:
df_custom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 16 columns):
id             32 non-null object
Unnamed: 1     32 non-null object
Unnamed: 2     32 non-null int64
Unnamed: 3     32 non-null int64
Unnamed: 4     32 non-null int64
Unnamed: 5     32 non-null int64
Unnamed: 6     32 non-null int64
Unnamed: 7     32 non-null int64
Unnamed: 8     32 non-null int64
Unnamed: 9     32 non-null int64
Unnamed: 10    32 non-null int64
Unnamed: 11    32 non-null int64
Unnamed: 12    32 non-null float64
Unnamed: 13    32 non-null float64
Unnamed: 14    32 non-null float64
Unnamed: 15    32 non-null float64
dtypes: float64(4), int64(10), object(2)
memory usage: 4.1+ KB

In [22]:
df_ids = df_custom.iloc[:, 0:2]

In [28]:
df_ids.to_dict('split')

{'index': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31],
 'columns': ['id', 'Unnamed: 1'],
 'data': [['S12000033', 'Aberdeen City'],
  ['S12000034', 'Aberdeenshire'],
  ['S12000041', 'Angus'],
  ['S12000035', 'Argyll and Bute'],
  ['S12000036', 'City of Edinburgh'],
  ['S12000005', 'Clackmannanshire'],
  ['S12000006', 'Dumfries and Galloway'],
  ['S12000042', 'Dundee City'],
  ['S12000008', 'East Ayrshire'],
  ['S12000045', 'East Dunbartonshire'],
  ['S12000010', 'East Lothian'],
  ['S12000011', 'East Renfrewshire'],
  ['S12000014', 'Falkirk'],
  ['S12000015', 'Fife'],
  ['S12000046', 'Glasgow City'],
  ['S12000017', 'Highland'],
  ['S12000018', 'Inverclyde'],
  ['S12000019', 'Midlothian'],
  ['S12000020', 'Moray'],
  ['S12000013', 'Na h-Eileanan Siar'],
  ['S12000021', 'North Ayrshire'],
  ['S12000044', 'North Lanarkshire'],
  ['S12000023', 'Orkney Islands'],
  ['S12000024', 'Perth and Kinross'],
  ['S12000038', 'Renfrewshire'],
  ['S12000026', 'Scottish Borders'],
  ['S12000027', 'Shetland Islands'],
  ['S12000028', 'South Ayrshire'],
  ['S12000029', 'South Lanarkshire'],
  ['S12000030', 'Stirling'],
  ['S12000039', 'West Dunbartonshire'],
  ['S12000040', 'West Lothian']]}